[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem"]

[build]
target = "x86-unknown-none.json"
rustflags = [
    # "-C", "link-arg=-Tlink.ld", # see build.rs
    "-C", "relocation-model=pic",
]
