[build]
target = "x86_64-unknown-none"
rustflags = [
    # We set up page tables anyway, hence, we do not need position indepentent
    # Rust code. The boot code itself (written in Assembly) stays unaffected
    # from this.
    "-C", "relocation-model=static",
    # "-C", "linker=ld",
    # "-C", "link-arg=-M",
]
