# This file gets automatically recognized each time
# we run "cargo check|build|...".

# We need to cross-compile the core library.
[unstable]
build-std = [
    "core",
    "compiler_builtins",
    "alloc",
]
build-std-features = ["compiler-builtins-mem"]

[build]
# target = "x86_64-unknown-none-static.json"
rustflags = [
    # We set up page tables anyway, hence, we do not need position independent
    # Rust code. The boot code itself (written in Assembly) stays unaffected
    # by this. Hence, the ELF will not have relocation information. GRUB
    # couldn't cope with them anyway when it chainloads this via Multiboot2.
    # All other compilatino options are derived from the compiler target spec:
    # https://github.com/rust-lang/rust/blob/master/compiler/rustc_target/src/spec/x86_64_unknown_none.rs
    "-C", "relocation-model=static",

    # "-C", "linker=ld", # sometimes helpful for better error messages
    # "-C", "link-arg=-M", # print memory link map: only works with GNU ld
]
