[package]
name = "phipsboot"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lib = { path = "../lib" }
good_memory_allocator = "0.1.7"
log = { version = "0.4.19", default-features = false }
multiboot2 = "0.16.0"
uart_16550 = "0.3.0"
x86 = "0.52.0"
x86_64 = "0.14.11"
