[package]
name = "bin"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lib = { path = "../lib" }
good_memory_allocator = "0.1.7"
multiboot2 = "0.16.0"
x86 = "0.52.0"
