[workspace]
resolver = "2"
members = [
    "bin",
    "lib",
]

[profile.dev]
panic = "abort"

[profile.release]
codegen-units = 1
# lto = true
opt-level = 1
# opt-level = "s" # size optimization
# strip = "debuginfo"
debug = true
panic = "abort"
