# https://rust-lang.github.io/rustup/overrides.html

[toolchain]
channel = "1.72"
# channel = "nightly-2023-08-31" # 1.74
components = [ "rust-std", "rustc", "cargo", "clippy", "rustfmt" ]
targets = [ "x86_64-unknown-none" ]
